Complete rewrite to be more robust and portable

diff --git a/dmenu b/dmenu
--- a/dmenu
+++ b/dmenu
@@ -1,24 +1,55 @@
 #!/bin/sh
 #
-# Specify some defaults for dmenu.
+# dmenu: Specify some defaults for dmenu.
 #
-# If programs want to override this, make sure they use the full path to dmenu.
+# Copyright 2010 Tom Vincent <http://www.tlvince.com/>
+#
+# This program is free software: you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation, either version 3 of the License, or
+# (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program. If not, see <http://www.gnu.org/licenses/>.
+#
+# Depends:
+# * coreutils
+# * dmenu
+#
+# Exit codes:
+#   0   - successful
+#   1   - bad argument
+#   2   - file not found
 
-# Imports:
-. "$HOME/proj/src/bash/lib/realBin.sh"
+# Global variables:
+WD="$(dirname "$(readlink -f "$0")")"     # Handle symlinks
 
-
-DMENU=$(realBin dmenu)
-if [[ $? -gt 0 ]]; then
-    echo "dmenu binary cannot be found. Have you installed dmenu?"
-    exit 1
-fi
-
-# Colours:
+## dmenu options:
 NORM_BG="#101010"
 NORM_FG="#777777"
 SELC_BG="#000000"
 SELC_FG="#ffffff"
 FONT="-*-terminus-medium-r-*-*-*-*-*-*-*-*-*-*"
 
-$DMENU -i -nb $NORM_BG -nf $NORM_FG -sb $SELC_BG -sf $SELC_FG -fn $FONT ${1+"$@"}
+# Imports:
+. "$WD/lib/realBin.sh"
+. "$WD/lib/logging.sh"
+
+##
+# Get the path to the dmenu binary, otherwise exit.
+#
+getDmenu()
+{
+    realBin dmenu
+    if [[ $? -gt 0 ]]; then
+        die "dmenu binary cannot be found. Have you installed dmenu?" 2
+    fi
+}
+
+dmenu="$(getDmenu)" || exit
+"$dmenu" -i -nb $NORM_BG -nf $NORM_FG -sb $SELC_BG -sf $SELC_FG -fn $FONT ${1+"$@"}
